config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  root  'static_pages#home'

  get '/home',     to: 'static_pages#home'
  get '/kitchens', to: 'static_pages#kitchens'
  get '/ourworks', to: 'static_pages#ourworks'
  get '/livingbaby', to: 'static_pages#livingbaby'
  get '/officefurniture', to: 'static_pages#officefurniture'
  get '/wardrobes', to: 'static_pages#wardrobes'
  get '/cloakroom', to: 'static_pages#cloakroom'
  get '/hallways', to: 'static_pages#hallways'

  match 'submit', to: 'submits#cors', via: :options
  match 'submit', to: 'submits#create', via: [:get, :post]

  resources :translations, only: :create
  resources :reviews, only: [:index, :new, :create]

  get ":category_slug", to: 'categories#show'
  get ":category_slug/:subcategory_slug", to: 'subcategories#show'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId

  has_many :subcategories
  has_many :types
  has_one  :promotion, dependent: :destroy

  validates :image, presence: true

  mount_uploader :image, ImageUploader

  friendly_id :slug_candidates, use: :slugged

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :russian).to_s
  end

  def slug_candidates
    [:title, :id]
  end

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/models/database_backup.rb
class DatabaseBackup < ActiveRecord::Base
  validates :file, :processed_at, presence: true
  mount_uploader :file, BackupUploader
end

app/models/furniture.rb
class Furniture < Project

end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :project

  mount_uploader :image, ImageUploader

  private

  # this method should use only to recreate versions of images
  def self.recreate_all_versions
    self.all.each do |image|
      image.image.recreate_versions!
      image.save
    end
  end
end

app/models/portfolio.rb
class Portfolio < Project

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :category
  belongs_to :subcategory
  belongs_to :type

  has_many   :images, dependent: :destroy

  validates :category, :subcategory, :type, presence: true

  before_save :set_date

  private

  def set_date
    self.creation_date = created_at if creation_date.blank?
  end
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  validates :category_id, presence: true, uniqueness: true

  belongs_to :category

  mount_uploader :image, ImageUploader

end

app/models/review.rb
class Review < ApplicationRecord
  mount_uploader  :avatar, AvatarUploader

  mount_uploaders :images, ImageUploader
  serialize :images, JSON

  belongs_to :portfolio

  validates_presence_of :name, :message, :portfolio
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  extend FriendlyId

  belongs_to :category
  has_many   :furniture
  has_many   :portfolios

  mount_uploader :image, ImageUploader

  validates :category, presence: true

  friendly_id :slug_candidates, use: :slugged

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :russian).to_s
  end

  def slug_candidates
    [:title, :id]
  end

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/models/submit.rb
class Submit < ApplicationRecord

  mount_uploader :file, ImageUploader

  enum submit_type: [:common, :callback, :metering, :calculation, :application]

  belongs_to :project
end

app/models/translation.rb
class Translation < ApplicationRecord
  after_save :clear_rails_cache
  after_destroy :clear_rails_cache

  validates :key, :language, presence: true
  validates :key, uniqueness: { scope: :language }

  def self.find_text(key)
    Rails.cache.fetch("#{key}_#{I18n.locale}") do
      Translation.find_by(key: key, language: I18n.locale).try :content
    end
  end

  def clear_rails_cache
    Rails.cache.delete("#{key}_#{I18n.locale}")
  end
end

app/models/type.rb
class Type < ApplicationRecord
  belongs_to :category
  has_many   :furnitures

  validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.where(displayable: true)
  end

  def new
    @review = Review.new
    @categories = Category.all
  end

  def create
    @review = Review.new(review_params)
    @review.images = [] if params[:review][:use_catalog?] == '1' && @review.valid?
    if @review.save
      redirect_to reviews_path
    else
      flash[:danger] = set_error_messages(@review)
      render 'new'
    end
  end

  private

  def review_params
    params.require(:review).permit(:name, :message, :avatar, :portfolio_id, { images: [] })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/editable_helper.rb
module EditableHelper

  def editable(key, text = nil, options= {}, &block)
    translation = Translation.find_text(key)
    if translation.present?
      content = translation
    else
      content = text.present? ? text : capture(&block)
    end
    return content.html_safe if current_user.nil? || options[:nowrap]
    ["<span class=\"editable editable-text\">",
     "<a href='#' data-editable='#{key}' class='edit-link'>",
     '<i class="fa fa-edit"></i>',
     '</a>',
     '<span class="editable-content">',
     content,
     '</span></span>'
    ].join.html_safe
  end

  def editable_link(key, text = nil, options= {}, &block)
    content = Translation.find_text(key) || text || capture(&block)
    return content.html_safe if current_user.nil? || options[:nowrap]
    ["<div href='#' data-editable='#{key}' class='edit-link edit-link-left'>",
      '<i class="fa fa-edit"></i>',
      "</div>",
      "<span class=\"editable editable-text\">",
     content,
     '</span>'
    ].join.html_safe
  end

  def editable_image_tag(key, options = {})
    source = Image.find_replacement(key) || key
    return image_tag(source, options) unless current_user.present?
    image_tag(asset_path(source), options.merge('data-editable-image' => key))
  end

end

app/helpers/ivm_pages_helper.rb
module IvmPagesHelper
end

app/views/active_admin_multi_upload/_upload_form.html.erb
<%= stylesheet_link_tag "active_admin_multi_upload/jquery_upload" %>


<%  options = options ||= {}
    uploaded_ids_form_input_name = options[:uploaded_ids_form_input_name] ||= "#{resource.class.name.underscore}[#{association.singularize}_ids][]"
    existing_uploads = options[:existing_uploads] ||= resource.send(association.to_sym)
    input_id_prefix = options[:input_id_prefix] ||= "#{resource.class.name.underscore}_#{association.singularize}_ids_"
    post_url = options[:post_url] ||= "/admin/#{association}/create_upload"
    input_name = options[:input_name] ||= "#{association.singularize.underscore}[#{attribute}]"
    uploader_id = options[:uploader_name] ||= "#{association}_uploader"
 %>

<div id="<%= uploader_id %>" class="uploader">
  <% if @furniture.present? %>
    <%= hidden_field_tag 'furniture_id', @furniture.id %>
  <% end %>
  <% if @project_example.present? %>
    <%= hidden_field_tag 'project_example_id', @project_example.id %>
  <% end %>
  <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
  <div class="row fileupload-buttonbar">
    <div class="span7">
    <!-- The fileinput-button span is used to style the file input field as button -->
      <span class="btn btn-success fileinput-button">
        <i class="icon-plus icon-white"></i>
        <span>Add files...</span>
        <input id="fileupload_<%= uploader_id %>" type="file" name="<%= input_name %>" multiple>
      </span>
      <button type="reset" class="btn btn-warning cancel">
        <i class="icon-ban-circle icon-white"></i>
        <span>Cancel upload</span>
      </button>
      <button type="button" class="btn btn-danger delete">
        <i class="icon-trash icon-white"></i>
        <span>Delete</span>
      </button>
      <input type="checkbox" class="toggle">
    </div>
  </div>
  <!-- The loading indicator is shown during image processing -->
  <div class="fileupload-process"></div>
  <br>
  <!-- The table listing the files available for upload/download -->
  <table class="table table-striped"><tbody class="files" id="<%= uploader_id %>-files-container" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody></table>
</div>


<script>
  var fileUploadErrors = {
    maxFileSize: 'File is too big',
    minFileSize: 'File is too small',
    acceptFileTypes: 'Filetype not allowed',
    maxNumberOfFiles: 'Max number of files exceeded',
    uploadedBytes: 'Uploaded bytes exceed file size',
    emptyResult: 'Something went wrong. Please try again'
};
</script>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
      <td class="preview"><span class="fade"></span></td>
      <td class="name"><span>{%=file.name%}</span></td>
      <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
      {% if (file.error) { %}
        <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
      {% } else if (o.files.valid && !i) { %}
        <td>
          <div class="progress progress-striped active" role="progressbar" ><div class="progress-bar bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td class="start">{% if (!o.options.autoUpload) { %}
          <button class="btn btn-primary">
            <i class="icon-upload icon-white"></i>
            <span>{%=locale.fileupload.start%}</span>
          </button>
      {% } %}</td>
      {% } else { %}
        <td colspan="2"></td>
      {% } %}
      <td class="cancel">{% if (!i) { %}
        <button class="btn btn-warning">
          <i class="icon-ban-circle icon-white"></i>
          <span>{%=locale.fileupload.cancel%}</span>
        </button>
      {% } %}</td>
    </tr>
  {% } %}
</script>

<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
      {% if (file.error) { %}
        <td></td>
        <td class="url"><span>{%=file.url%}</span></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
      {% } else { %}
        <td class="preview">{% if (file.thumbnail_url) { %}
          <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}">
            <img src="{%=file.url%}" width="200px">
          </a>
        {% } %}</td>
        <td class="name" id="upload_{%=file.id%}" data-id="{%=file.id%}">
          <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}
            <img src="{%=file.url%}" width="200px">
          </a>
        </td>
        <td class="url"><span>{%=file.url%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td colspan="2"></td>
      {% } %}
      <td class="delete">
        <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
          <i class="icon-trash icon-white"></i>
          <span>{%=locale.fileupload.destroy%}</span>
        </button>
        <input type="checkbox" name="delete" value="1">
      </td>
    </tr>
  {% } %}
</script>


<script type="text/javascript" charset="utf-8">
  $(function () {
  // Initialize the jQuery File Upload widget:
    $("#<%= uploader_id %>").fileupload({
      url: "<%= post_url %>",
      autoUpload: true,
      formData: { },
      sequentialUploads: true,
      fileInput: $("#fileupload_<%= uploader_id %>"),
      filesContainer: "#<%= uploader_id %>-files-container"
    }).on('fileuploadcompleted', function(e, data) {
      insertUploadInputsFor<%= association.capitalize %>(data.result.files);
    }).bind('fileuploaddestroy', function(e, data) {
      removeUploadInputsFor<%= association.capitalize %>([data]);
    });
  });
</script>


<script type="text/javascript">

var insertUploadInputsFor<%= association.capitalize %> = function(files) {
  $.each(files, function(index, file) {
      var input = $("<input type='hidden' class='file-upload' name='<%= uploaded_ids_form_input_name %>' id='<%= input_id_prefix %>" + file.id + "' value='" + file.id + "' />");
      input.insertAfter($("#upload_" + file.id));
  });
};

var removeUploadInputsFor<%= association.capitalize %> = function(files) {
  $.each(files, function(index, file) {
    var id = file.url.split("/").pop();
    $("#<%= input_id_prefix %>" + id).remove();
  });
};

$(function () {
  var files = <%= existing_uploads.map(&:to_jq_upload).to_json.html_safe %>;
  var uploader = $("#<%= uploader_id %>").data("blueimpFileupload");
  var template = uploader._renderDownload(files)['appendTo'](uploader.options.filesContainer);
  uploader._transition(template);
  insertUploadInputsFor<%= association.capitalize %>(files);
});

</script>

app/views/active_admin_multi_upload/upload_form.html.erb
<%= stylesheet_link_tag "active_admin_multi_upload/jquery_upload" %>


<%  options = options ||= {}
    uploaded_ids_form_input_name = options[:uploaded_ids_form_input_name] ||= "#{resource.class.name.underscore}[#{association.singularize}_ids][]"
    existing_uploads = options[:existing_uploads] ||= resource.send(association.to_sym)
    input_id_prefix = options[:input_id_prefix] ||= "#{resource.class.name.underscore}_#{association.singularize}_ids_"
    post_url = options[:post_url] ||= "/admin/#{association}/create_upload"
    input_name = options[:input_name] ||= "#{association.singularize.underscore}[#{attribute}]"
    uploader_id = options[:uploader_name] ||= "#{association}_uploader"

 %>

<div id="<%= uploader_id %>" class="uploader">
  <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
  <div class="row fileupload-buttonbar">
    <div class="span7">
    <!-- The fileinput-button span is used to style the file input field as button -->
      <span class="btn btn-success fileinput-button">
        <i class="icon-plus icon-white"></i>
        <span>Add files...</span>
        <input id="fileupload_<%= uploader_id %>" type="file" name="<%= input_name %>" multiple>
      </span>
      <button type="reset" class="btn btn-warning cancel">
        <i class="icon-ban-circle icon-white"></i>
        <span>Cancel upload</span>
      </button>
      <button type="button" class="btn btn-danger delete">
        <i class="icon-trash icon-white"></i>
        <span>Delete</span>
      </button>
      <input type="checkbox" class="toggle">
    </div>
  </div>
  <!-- The loading indicator is shown during image processing -->
  <div class="fileupload-process"></div>
  <br>
  <!-- The table listing the files available for upload/download -->
  <table class="table table-striped"><tbody class="files" id="<%= uploader_id %>-files-container" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody></table>
</div>


<script>
  var fileUploadErrors = {
    maxFileSize: 'File is too big',
    minFileSize: 'File is too small',
    acceptFileTypes: 'Filetype not allowed',
    maxNumberOfFiles: 'Max number of files exceeded',
    uploadedBytes: 'Uploaded bytes exceed file size',
    emptyResult: 'Something went wrong. Please try again'
};
</script>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
      <td class="preview"><span class="fade"></span></td>
      <td class="name"><span>{%=file.name%}</span></td>
      <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
      {% if (file.error) { %}
        <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
      {% } else if (o.files.valid && !i) { %}
        <td>
          <div class="progress progress-striped active" role="progressbar" ><div class="progress-bar bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td class="start">{% if (!o.options.autoUpload) { %}
          <button class="btn btn-primary">
            <i class="icon-upload icon-white"></i>
            <span>{%=locale.fileupload.start%}</span>
          </button>
      {% } %}</td>
      {% } else { %}
        <td colspan="2"></td>
      {% } %}
      <td class="cancel">{% if (!i) { %}
        <button class="btn btn-warning">
          <i class="icon-ban-circle icon-white"></i>
          <span>{%=locale.fileupload.cancel%}</span>
        </button>
      {% } %}</td>
    </tr>
  {% } %}
</script>

<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
      {% if (file.error) { %}
        <td></td>
        <td class="url"><span>{%=file.url%}</span></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
      {% } else { %}
        <td class="preview">{% if (file.thumbnail_url) { %}
          <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}">
            <img src="{%=file.url%}" width="200px">
          </a>
        {% } %}</td>
        <td class="name" id="upload_{%=file.id%}" data-id="{%=file.id%}">
          <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}
            <img src="{%=file.url%}" width="200px">
          </a>
        </td>
        <td class="url"><span>{%=file.url%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td colspan="2"></td>
      {% } %}
      <td class="delete">
        <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
          <i class="icon-trash icon-white"></i>
          <span>{%=locale.fileupload.destroy%}</span>
        </button>
        <input type="checkbox" name="delete" value="1">
      </td>
    </tr>
  {% } %}
</script>


<script type="text/javascript" charset="utf-8">
  $(function () {
  // Initialize the jQuery File Upload widget:
    $("#<%= uploader_id %>").fileupload({
      url: "<%= post_url %>",
      autoUpload: true,
      formData: {},
      sequentialUploads: true,
      fileInput: $("#fileupload_<%= uploader_id %>"),
      filesContainer: "#<%= uploader_id %>-files-container"
    }).on('fileuploadcompleted', function(e, data) {
      insertUploadInputsFor<%= association.capitalize %>(data.result.files);
    }).bind('fileuploaddestroy', function(e, data) {
      removeUploadInputsFor<%= association.capitalize %>([data]);
    });
  });
</script>


<script type="text/javascript">

var insertUploadInputsFor<%= association.capitalize %> = function(files) {
  $.each(files, function(index, file) {
      var input = $("<input type='hidden' class='file-upload' name='<%= uploaded_ids_form_input_name %>' id='<%= input_id_prefix %>" + file.id + "' value='" + file.id + "' />");
      input.insertAfter($("#upload_" + file.id));
  });
};

var removeUploadInputsFor<%= association.capitalize %> = function(files) {
  $.each(files, function(index, file) {
    var id = file.url.split("/").pop();
    $("#<%= input_id_prefix %>" + id).remove();
  });
};

$(function () {
  var files = <%= existing_uploads.map(&:to_jq_upload).to_json.html_safe %>;
  var uploader = $("#<%= uploader_id %>").data("blueimpFileupload");
  var template = uploader._renderDownload(files)['appendTo'](uploader.options.filesContainer);
  uploader._transition(template);
  insertUploadInputsFor<%= association.capitalize %>(files);
});

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IVM мебель</title>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'icon.png' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'partials/header_new' %>
  <%= render 'partials/banner' %>
  <div class="min-menu">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= content_for(:breadcrumbs) %>
        </div>
      </div>
    </div>
  </div>
  <%= yield %>
  <%= render 'partials/footer' %>
</body>
</html>

app/views/partials/_alert.html.erb
<% flash.each do |status, messages| %>
  <% next if messages.blank? %>
  <% messages = [messages] if messages.class.to_s == 'String' %>
  <div class="alert alert-<%= status.to_s %>" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= messages.join('<br>').html_safe %>
  </div>
<% end %>

app/views/partials/_banner.html.erb
<div class="container-fluid alert alert-danger" style="margin-top: 20px; border: none; border-radius: 0;">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3 class="text-center" style="margin: 20px 0;">На данный момент сайт находится на стадии доработки/наполнения.</h3>
      </div>
    </div>
  </div>
</div>

app/views/partials/_catalog_dropdown_new.html.erb
<div class="row">
  <ul class="list-group col-md-3 js-catalog-menu">
    <% @all_categories.each do |cat| %>
      <li class="list-group-item js-menu-item <%= "develop" if cat.in_development %>"
          data-block="<%= cat.in_development ? "in-development" : cat.slug %>">
        <a href="/<%= cat.slug %>"><%= cat.title %></a>
      </li>
    <% end %>
  </ul>

  <div class="col-md-9 div-items">
    <% @all_categories.each do |cat| %>
      <div class="kitchen-links visible <%= cat.slug %>">
        <% cat.subcategories.each do |subcat| %>
          <div class="col-md-3 link-container">
            <div class="bg-image" style="background-image: url(<%= subcat.image_url.present? ? subcat.image_url(:small) : asset_path("1.png") %>)"></div>

            <a href="<%= "/#{cat.slug}/#{subcat.slug}" %>" class="more">
              <span><%= subcat.title %></span>
            </a>
          </div>
        <% end %>
      </div>
    <% end %>

    <div class="kitchen-links in-development">
      <p>РАЗДЕЛ В РАЗРАБОТКЕ</p>
    </div>
  </div>
</div>

app/views/partials/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row">
      <!-- social -->
      <div class="social">
        <p class="soc">
          індивідуальне
          виробництво
          меблів
        </p>

        <div class="social-ico-menu">
          <a href="#"><%= fa_icon "facebook" %></a>
          <a href="#"><%= fa_icon "vk" %></a>
          <a href="#"><%= fa_icon "twitter" %></a>
          <a href="#"><%= fa_icon "google" %></a>
        </div>
      </div>
      
      <!-- contanct -->
      <div class="contact">
        <span class="ico"></span>
        <p class="ico-text"><%= editable :kyivstar, '096(548) 38-81' %></p>
        <p class="text"><%= editable :lifecell, '093(607) 28-24' %></p>
        <p class="text"><%= editable :vodafone, '066(466) 28-01' %></p>
        <span class="ico ico-mail"></span>
        <p class="ico-text"><%= editable :ivm_email, 'office@ivm.com.ua' %></p>
      </div>

      <!-- address -->
      <div class="address">
        <span class="ico ico-dot"></span>
        <p class="ico-text adr"><%= editable :ivm_address, 'м. Київ, вул. Новоконстантинівська, 1В' %></p>
        <div class="pad">
          <span class="ico ico-taime"></span>
          <p class="ico-text"><%= editable :time_schedule_1, 'Графік роботи: з 09.00 до 20.00' %></p>
          <p class="text"><%= editable :time_schedule_2, 'Без вихідних' %></p>
        </div>
      </div>

      <div class="map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6038.765340843853!2d30.4926729538119!3d50.47856592664192!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40d4cde1e8987bf9%3A0x253d220a11013d3e!2zSVZNINGW0L3QtNC40LLRltC00YPQsNC70YzQvdC1INCy0LjQs9C-0YLQvtCy0LvQtdC90L3RjyDQvNC10LHQu9GW0LI!5e0!3m2!1sru!2sua!4v1500897309218"
                width="100%" height="240" frameborder="0" style="border:0" allowfullscreen>
        </iframe>
      </div>
    </div>
  </div>
</div>