config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  root  'static_pages#home'

  get '/home',     to: 'static_pages#home'
  get '/kitchens', to: 'static_pages#kitchens'
  get '/ourworks', to: 'static_pages#ourworks'
  get '/livingbaby', to: 'static_pages#livingbaby'
  get '/officefurniture', to: 'static_pages#officefurniture'
  get '/wardrobes', to: 'static_pages#wardrobes'
  get '/cloakroom', to: 'static_pages#cloakroom'
  get '/hallways', to: 'static_pages#hallways'

  match 'submit', to: 'submits#cors', via: :options
  match 'submit', to: 'submits#create', via: [:get, :post]

  resources :translations, only: :create
  resources :reviews, only: [:index, :new, :create]

  get ":category_slug", to: 'categories#show'
  get ":category_slug/:subcategory_slug", to: 'subcategories#show'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.where(displayable: true)
  end

  def new
    @review = Review.new
    @categories = Category.all
  end

  def create
    @review = Review.new(review_params)
    @review.images = [] if params[:review][:use_catalog?] == '1' && @review.valid?
    if @review.save
      redirect_to reviews_path
    else
      flash[:danger] = set_error_messages(@review)
      render 'new'
    end
  end

  private

  def review_params
    params.require(:review).permit(:name, :message, :avatar, :portfolio_id, { images: [] })
  end
end

app/views/reviews/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 reviews-wrapper">
      <div class="col-md-12" id="slick-review">
        <% @reviews.each do |review| %>
          <% review.images.blank? ? images = review.portfolio.images.map(&:image) : images = review.images %>
          <div class="each-review">
            <div class="col-md-2 col-sm-5 review-avatar no-padd">
              <% unless review.avatar.blank? %>
                <%= image_tag review.avatar_url(:thumb), alt: 'ivm-review', class: 'img-circle' %>
              <% end %>
            </div>
            <div class="col-md-2 col-sm-5 review-name">
              <p><%= review.name %></p>
            </div>
            <div class="col-md-7 col-sm-12 review-description">
              <p class="text-justify"><%= review.message %></p>
            </div>
            <div class="col-md-12 review-thumbnails">
              <% images.first(4).each do |img| %>
                <div class="col-md-3 col-sm-4 col-xs-6 each-element " data-toggle="modal-with-slider" data-target="<%= review.portfolio.id%>">
                  <%= image_tag img.url(:medium_fill), alt: "ivm logo", class: 'background'  %>
                  <div class="image-text">
                    <%= image_tag "zoom.png", alt: "ivm logo", class: 'zoom'  %>
                    <span class="title"></span>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 new-review-block">
      <%= link_to 'Оставить отзыв', new_review_path %>
    </div>
  </div>
</div>

<% @reviews.each do |review| %>
  <% review.images.blank? ? images = review.portfolio.images.map(&:image) : images = review.images %>
  <div class="modal fade" id="lightslider-modal-<%= review.portfolio.id %>" tabindex="-1" role="dialog" aria-labelledby="lightslider-modal-ModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div type="button" class="close close-pos" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><%= image_tag('close-img.png', class: "close-button") %></span>
      </div>
      <div class="modal-content mdf-modal">
        <div class="modal-body">
          <div class="col-md-8">
            <div id="owl-mdf-<%= review.id %>" class="js-slick-carousel">
              <% images.each do |img| %>
                <div class="item">
                  <%= image_tag img.url, alt: "ivm" %>
                </div>
              <% end %>
            </div>
            <div class="col-md-12">
              <h1 class="main-title text-center"><%= review.portfolio.title %></h1>
              <div class="text"><%= review.portfolio.description.html_safe %></div>
            </div>
          </div>

          <div class="col-md-4">
            <% allow_scroll = images.count > 6 %>
            <button class="slimscroll-btn btn-up <%= 'btn-disabled' unless allow_scroll %>">
              <span class="fa fa-chevron-up"></span>
            </button>
            <div class="thumbs-carousel <%= 'js-thumbs-carousel' if allow_scroll %>">
              <% images.each_slice(2).with_index do |pair, index| %>
                <div class="col-md-12 no-padd pair-container">
                  <% i = index * 2 %>
                  <% pair.compact.each_with_index do |img, pair_i| %>
                    <% i = i + 1 if pair_i == 1 %>
                    <div class="col-md-6 col-sm-6 thumbnail-box js-jumpTo" data-jump-to="<%= i %>">
                      <%= image_tag img.url, alt: "ivm" %>
                    </div>
                  <% end %>
                </div>
              <% end %>
            </div>
            <button class="slimscroll-btn btn-down <%= 'btn-disabled' unless allow_scroll %>">
              <span class="fa fa-chevron-down"></span>
            </button>
            <div class="col-md-12 buttons-padd">
              <%= link_to "Узнать цену", '#', class: 'btn-send-app-user text-center', data: { toggle: 'modal', target: '#send-request-from-modal'} %>
              <button class="btn-send-call" data-toggle="modal" data-target="#callback-from-modal">
                <%= image_tag('btn-header-2.png') %>
                Заказать
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= render 'subcategories/item_modals' %>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <%= render 'partials/alert' %>
      <div class="review-form">
        <div class="col-md-12">
          <h4 class="form-header">Понравилась работа? Оставьте нам отзыв!</h4>
          <%= form_for @review do |f| %>
            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control simple-input' %>
            </div>
            <div class="form-group">
              <%= f.label :message %>
              <%= f.text_area :message, class: 'form-control simple-input', rows: 10 %>
            </div>
            <div class="form-group">
              <%= f.label :avatar, class: 'avatar-label' %><br>
              <%= f.file_field :avatar, id: 'user_avatar', class: 'file-btn js-file-btn' %>
              <label for="user_avatar" class="btn btn-attachment">
                <i class="fa fa-paperclip"></i>
                <span class="span-target" data-target-for="user_avatar">Выберите файл...</span>
              </label>
            </div>
            <div class="form-group no-margin">
              <%= label_tag 'Select furniture' %>
              <br>
              <input class="select2-ajax" data-fields="[&quot;title&quot;]" data-model="review" data-display_name="title" data-minimum_input_length="0" data-collection="null" id="review_category_id" data-url="/admin/categories" data-response_root="categories" data-selected="" name="review[category_id]" tabindex="-1">
              <br>
              <input class="select2-ajax" data-fields="[&quot;title&quot;]" data-model="review" data-display_name="title" data-minimum_input_length="0" data-collection="null" id="review_subcategory_id" data-url="/admin/subcategories" data-response_root="subcategories" data-selected="" data-parent="category_id" name="review[subcategory_id]">
              <br>
              <input class="select2-ajax" data-fields="[&quot;title&quot;]" data-model="review" data-display_name="title" data-minimum_input_length="0" data-collection="null" id="review_portfolio_id" data-url="/admin/portfolios" data-response_root="portfolios" data-selected="" data-parent="subcategory_id" name="review[portfolio_id]">
            </div>
            <div class="form-group">
              <%= f.label :images, class: 'avatar-label' %><br>
              <%= f.file_field :images, id: 'review_images', class: 'file-btn js-file-btn', multiple: true, data: { multiple_caption: '{count} выбранных файлов'} %>
              <label for="review_images" class="btn btn-attachment">
                <i class="fa fa-paperclip"></i>
                <span class="span-target" data-target-for="review_images">Выберите файлы...</span>
              </label>
              <div class="checkbox">
                <label>
                  <%= check_box_tag 'review[use_catalog?]' %>
                  Использовать фотографии из каталога. <small>(Ваши фотографии не попадут в отзыв)</small>
                </label>
              </div>
            </div>
            <div class="form-group review-submit">
              <%= f.submit 'Отправить отзыв', class: 'btn btn-lg btn-success' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>