config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  root  'static_pages#home'

  get '/home',     to: 'static_pages#home'
  get '/kitchens', to: 'static_pages#kitchens'
  get '/ourworks', to: 'static_pages#ourworks'
  get '/livingbaby', to: 'static_pages#livingbaby'
  get '/officefurniture', to: 'static_pages#officefurniture'
  get '/wardrobes', to: 'static_pages#wardrobes'
  get '/cloakroom', to: 'static_pages#cloakroom'
  get '/hallways', to: 'static_pages#hallways'

  match 'submit', to: 'submits#cors', via: :options
  match 'submit', to: 'submits#create', via: [:get, :post]

  resources :translations, only: :create
  resources :reviews, only: [:index, :new, :create]

  get ":category_slug", to: 'categories#show'
  get ":category_slug/:subcategory_slug", to: 'subcategories#show'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId

  has_many :subcategories
  has_many :types
  has_one  :promotion, dependent: :destroy

  validates :image, presence: true

  mount_uploader :image, ImageUploader

  friendly_id :slug_candidates, use: :slugged

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :russian).to_s
  end

  def slug_candidates
    [:title, :id]
  end

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/models/database_backup.rb
class DatabaseBackup < ActiveRecord::Base
  validates :file, :processed_at, presence: true
  mount_uploader :file, BackupUploader
end

app/models/furniture.rb
class Furniture < Project

end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :project

  mount_uploader :image, ImageUploader

  private

  # this method should use only to recreate versions of images
  def self.recreate_all_versions
    self.all.each do |image|
      image.image.recreate_versions!
      image.save
    end
  end
end

app/models/portfolio.rb
class Portfolio < Project

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :category
  belongs_to :subcategory
  belongs_to :type

  has_many   :images, dependent: :destroy

  validates :category, :subcategory, :type, presence: true

  before_save :set_date

  private

  def set_date
    self.creation_date = created_at if creation_date.blank?
  end
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  validates :category_id, presence: true, uniqueness: true

  belongs_to :category

  mount_uploader :image, ImageUploader

end

app/models/review.rb
class Review < ApplicationRecord
  mount_uploader  :avatar, AvatarUploader

  mount_uploaders :images, ImageUploader
  serialize :images, JSON

  belongs_to :portfolio

  validates_presence_of :name, :message, :portfolio
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  extend FriendlyId

  belongs_to :category
  has_many   :furniture
  has_many   :portfolios

  mount_uploader :image, ImageUploader

  validates :category, presence: true

  friendly_id :slug_candidates, use: :slugged

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :russian).to_s
  end

  def slug_candidates
    [:title, :id]
  end

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/models/submit.rb
class Submit < ApplicationRecord

  mount_uploader :file, ImageUploader

  enum submit_type: [:common, :callback, :metering, :calculation, :application]

  belongs_to :project
end

app/models/translation.rb
class Translation < ApplicationRecord
  after_save :clear_rails_cache
  after_destroy :clear_rails_cache

  validates :key, :language, presence: true
  validates :key, uniqueness: { scope: :language }

  def self.find_text(key)
    Rails.cache.fetch("#{key}_#{I18n.locale}") do
      Translation.find_by(key: key, language: I18n.locale).try :content
    end
  end

  def clear_rails_cache
    Rails.cache.delete("#{key}_#{I18n.locale}")
  end
end

app/models/type.rb
class Type < ApplicationRecord
  belongs_to :category
  has_many   :furnitures

  validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.where(displayable: true)
  end

  def new
    @review = Review.new
    @categories = Category.all
  end

  def create
    @review = Review.new(review_params)
    @review.images = [] if params[:review][:use_catalog?] == '1' && @review.valid?
    if @review.save
      redirect_to reviews_path
    else
      flash[:danger] = set_error_messages(@review)
      render 'new'
    end
  end

  private

  def review_params
    params.require(:review).permit(:name, :message, :avatar, :portfolio_id, { images: [] })
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @categories = Category.where(in_development: false).order(display_priority: :desc).limit(6)
    @last_projects_images = Portfolio.order(creation_date: :desc).map(&:images).flatten! || []
  end

  def kitchens
    @subcategory = Subcategory.all
    @furniture = Furniture.all
  end

  def ourworks
    @portfolios = Portfolio.all
    @show_project = params[:peid].to_i || nil
  end

  def livingbaby

  end

  def officefurniture

  end

  def wardrobes

  end

  def cloakroom

  end

  def hallways

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/editable_helper.rb
module EditableHelper

  def editable(key, text = nil, options= {}, &block)
    translation = Translation.find_text(key)
    if translation.present?
      content = translation
    else
      content = text.present? ? text : capture(&block)
    end
    return content.html_safe if current_user.nil? || options[:nowrap]
    ["<span class=\"editable editable-text\">",
     "<a href='#' data-editable='#{key}' class='edit-link'>",
     '<i class="fa fa-edit"></i>',
     '</a>',
     '<span class="editable-content">',
     content,
     '</span></span>'
    ].join.html_safe
  end

  def editable_link(key, text = nil, options= {}, &block)
    content = Translation.find_text(key) || text || capture(&block)
    return content.html_safe if current_user.nil? || options[:nowrap]
    ["<div href='#' data-editable='#{key}' class='edit-link edit-link-left'>",
      '<i class="fa fa-edit"></i>',
      "</div>",
      "<span class=\"editable editable-text\">",
     content,
     '</span>'
    ].join.html_safe
  end

  def editable_image_tag(key, options = {})
    source = Image.find_replacement(key) || key
    return image_tag(source, options) unless current_user.present?
    image_tag(asset_path(source), options.merge('data-editable-image' => key))
  end

end

app/helpers/ivm_pages_helper.rb
module IvmPagesHelper
end

app/views/static_pages/cloakroom.html.erb
<div class="kitchens">
  <div class="container">
    <div class="row">
      <ul class="list-group">
        <li class="list-group-item l"><%= link_to "ГЛАВНАЯ", root_path %></li>
        <li class="list-group-item l"><%= link_to "ГАРДЕРОБНЫЕ", root_path %></li>
      </ul>

      <div class="col-md-3 p-for-bar">
        <div class="sidebar">
          <ul>
            <li><%= link_to "ПЛЕНОЧНЫЙ МДФ", root_path %></li>
            <li><%= link_to "КРАШЕНЫЙ МДФ", root_path %></li>
            <li><%= link_to "ПЛАСТИКОВЫЕ", root_path %></li>
            <li><%= link_to "МДФ РАМОЧНЫЙ", root_path %></li>
            <li><%= link_to "СТЕКЛО В АЛЮМ.ПРОФИЛЕ", root_path %></li>
            <li><%= link_to "ФОТОФАСАДЫ", root_path %></li>
          </ul>

          <div class="news">
            <%= image_tag("fasad-news.png", :alt => "ivm logo") %>
          </div>
        </div>
      </div>
      <div class="col-md-9 content-kitchens">


      </div>
    </div>
  </div>
</div>



<div class="bd-example-3">
  <div class="modal fade" id="mdf-modal" tabindex="-1" role="dialog" aria-labelledby="mdf-modal-ModalLabel-2" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content mdf-modal">
        <div class="modal-body">
          <button type="button" class="close close-pos" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"><%= image_tag('close-img.png', class: "close-button") %></span>
          </button>
          <div class="col-md-8">
            <div id="owl-mdf" class="owl-carousel owl-theme">
              <div class="item">
                <%= image_tag("our-works-1.png", :alt => "ivm") %>
              </div>

              <div class="item">
                <%= image_tag("our-works-1.png", :alt => "ivm") %>
              </div>

              <div class="item">
                <%= image_tag("our-works-1.png", :alt => "ivm") %>
              </div>

              <div class="item">
                <%= image_tag("our-works-1.png", :alt => "ivm") %>
              </div>
            </div>
          </div>

          <div class="col-md-4">
            <h1 class="main-title">КРАШЕНЫЙ МДФ</h1>

            <div class="col-md-6 col-sm-6">
              <%= image_tag("k-1.png", :alt => "ivm") %>
            </div>

            <div class="col-md-6 col-sm-6">
              <%= image_tag("k-1.png", :alt => "ivm") %>
            </div>

            <div class="col-md-6 col-sm-6">
              <%= image_tag("k-1.png", :alt => "ivm") %>
            </div>

            <div class="col-md-6 col-sm-6">
              <%= image_tag("k-1.png", :alt => "ivm") %>
            </div>
            <div class="col-md-12 text">
              Чтобы узнать цену комплектации кухни
              по вашим размерам и предпочтениям
              Вы можете отправить заявку на расчет или
              заказать обратный звонок,
              и мы вам перезвоним!
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/hallways.html.erb
<div class="kitchens">
  <div class="container">
    <div class="row">
      <ul class="list-group">
        <li class="list-group-item l"><%= link_to "ГЛАВНАЯ", root_path %></li>
        <li class="list-group-item l"><%= link_to "ПРИХОЖИЕ", root_path %></li>
      </ul>

      <div class="col-md-3 p-for-bar">
        <div class="sidebar">
          <ul>
            <li><%= link_to "ПЛЕНОЧНЫЙ МДФ", root_path %></li>
            <li><%= link_to "КРАШЕНЫЙ МДФ", root_path %></li>
            <li><%= link_to "ПЛАСТИКОВЫЕ", root_path %></li>
            <li><%= link_to "МДФ РАМОЧНЫЙ", root_path %></li>
            <li><%= link_to "СТЕКЛО В АЛЮМ.ПРОФИЛЕ", root_path %></li>
            <li><%= link_to "ФОТОФАСАДЫ", root_path %></li>
          </ul>

          <div class="news">
            <%= image_tag("fasad-news.png", :alt => "ivm logo") %>
          </div>
        </div>
      </div>
      <div class="col-md-9 content-kitchens">


      </div>
    </div>
  </div>
</div>



<div class="bd-example-3">
  <div class="modal fade" id="mdf-modal" tabindex="-1" role="dialog" aria-labelledby="mdf-modal-ModalLabel-2" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content mdf-modal">
        <div class="modal-body">
          <button type="button" class="close close-pos" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"><%= image_tag('close-img.png', class: "close-button") %></span>
          </button>
          <div class="col-md-8">
            <div id="owl-mdf" class="owl-carousel owl-theme">
              <div class="item">
                <%= image_tag("our-works-1.png", :alt => "ivm") %>
              </div>

              <div class="item">
                <%= image_tag("our-works-1.png", :alt => "ivm") %>
              </div>

              <div class="item">
                <%= image_tag("our-works-1.png", :alt => "ivm") %>
              </div>

              <div class="item">
                <%= image_tag("our-works-1.png", :alt => "ivm") %>
              </div>
            </div>
          </div>

          <div class="col-md-4">
            <h1 class="main-title">КРАШЕНЫЙ МДФ</h1>

            <div class="col-md-6 col-sm-6">
              <%= image_tag("k-1.png", :alt => "ivm") %>
            </div>

            <div class="col-md-6 col-sm-6">
              <%= image_tag("k-1.png", :alt => "ivm") %>
            </div>

            <div class="col-md-6 col-sm-6">
              <%= image_tag("k-1.png", :alt => "ivm") %>
            </div>

            <div class="col-md-6 col-sm-6">
              <%= image_tag("k-1.png", :alt => "ivm") %>
            </div>
            <div class="col-md-12 text">
              Чтобы узнать цену комплектации кухни
              по вашим размерам и предпочтениям
              Вы можете отправить заявку на расчет или
              заказать обратный звонок,
              и мы вам перезвоним!
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<%= render 'static_pages/home/galleryimg', categories: @categories, prefix: nil %>
<%= render 'static_pages/home/howwework' %>
<%= render 'static_pages/home/othersproj' %>
<%= render 'static_pages/home/info' %>

app/views/static_pages/home/_galleryimg.html.erb
<div class="content">
  <div class="container">
    <div class="row">
      <% categories.each do |cat| %>
        <div class="col-md-4 col-sm-6">
          <div class="gallery-img" style="background-image: url(<%= cat.image_url(:big_menu) %>);">
            <%= link_to cat.title, [prefix, cat.slug].join('/') %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/static_pages/home/_howwework.html.erb
<%# howwework block %>
<div class="howwework">
  <div class="container">
    <div class="col-md-7 left">
      <div class="row">
        <h1 class="main-title">Как мы работаем</h1>

        <div class="box">
          <%= image_tag("1-round.png", :alt => "ivm logo", class: "pull-left img-step wow") %>

          <div class="pull-left right-box wow">
            <h1 class="title">ЗАЯВКА / ЭСКИЗ</h1>
            <h1 class="post-title">ПРОФЕССИОНАЛЬНАЯ КОНСУЛЬТАЦИЯ!</h1>
            <p class="text">Наши менеджеры дадут ответ на все вопросы и подскажут как правильно обустроить мебель.</p>
          </div>
        </div>

        <div class="box">
          <%= image_tag("2-round.png", :alt => "ivm logo", class: "pull-left img-step wow") %>

          <div class="pull-left right-box wow">
            <h1 class="title">ЗАМЕР / ДОГОВОР</h1>
            <h1 class="post-title">МАКСИМАЛЬНО ВЫГОДНЫЕ УСЛОВИЯ!</h1>
            <p class="text">— автоматизированное производство;</p>
            <p class="text">— прозрачная схема просчета стоимости заказа.</p>
          </div>
        </div>

        <div class="box">
          <%= image_tag("3-round.png", :alt => "ivm logo", class: "pull-left img-step wow") %>

          <div class="pull-left right-box wow">
            <h1 class="title">ПРОИЗВОДСТВО</h1>
            <h1 class="post-title">ВЫСОКОЕ КАЧЕСТВО РАБОТЫ!</h1>
            <p class="text">— использование новейшего ОБОРУДОВАНИЯ;</p>
            <p class="text">— сертифицированные материалы от производителя;</p>
            <p class="text">— только профессиональные работники.</p>
          </div>
        </div>

        <div class="box bottom-box">
          <%= image_tag("4-round.png", :alt => "ivm logo", class: "pull-left img-step wow") %>

          <div class="pull-left right-box wow">
            <h1 class="title">ДОСТАВКА / УСТАНОВКА</h1>
            <p class="text">
              Как только мы выполним заказ, с Вами свяжется представитель и договориться о доставке.
              Мастера оперативно и качественно произведут монтаж в удобное время.
            </p>
          </div>
        </div>

      </div>
    </div>

    <div class="col-md-5 right">
      <div class="row">
        <h1 class="main-title send-title">ОСТАВЬТЕ ЗАЯВКУ!</h1>
        <div class="form">
          <div class="wrapper">
            <%= form_tag('', class: 'js-common-request', method: 'post') do %>
              <%= text_field_tag 'common[name]', nil, placeholder: 'Ваше имя', class: "name-user", :required => true %>
              <%= text_field_tag 'common[phone]', nil, placeholder: 'Номер телефона', pattern:'[+]\d{2}[(]\d{3}[)]\s\d{3}\s\d{2}\s\d{2}', class: "phone-user", :required => true %>
              <%= text_field_tag 'common[message]', nil, placeholder: 'Сообщение', class: "mess-user" %>
              <%= submit_tag("Отправить заявку", class: "btn-send-app-user") %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<%# howwework block end %>

app/views/static_pages/home/_othersproj.html.erb
<div class="othersproj">
  <div class="container">
    <div class="row">
      <div class="line">
        <h1 class="projects">Последние проекты</h1>
      </div>

      <div id="slick-demo">
        <% @last_projects_images.each do |slider_img| %>
          <div class="item">
            <%= image_tag(slider_img.image.url(:medium_fill), alt: "ivm logo", class: "img-proj") %>
            <span class="date"><%= slider_img.project.creation_date %></span>
            <%= link_to "Смотреть подробнее", ourworks_path(peid: slider_img.project.category.id), class: 'more' %>
          </div>
        <% end %>
      </div>
      <div class="line-bg"></div>
    </div>
  </div>
</div>

app/views/static_pages/kitchens.html.erb
<div class="kitchens">
  <div class="container">
    <div class="row">
      <ul class="list-group">
        <li class="list-group-item l"><%= link_to "ГЛАВНАЯ", root_path %></li>
        <li class="list-group-item l"><%= link_to "КУХНИ", root_path %></li>
        <li class="list-group-item"><%= link_to "КУХНИ МОДЕРН", root_path %></li>
      </ul>

      <div class="col-md-3 p-for-bar">
        <div class="sidebar">
          <ul>
            <li><%= link_to "ПЛЕНОЧНЫЙ МДФ", root_path %></li>
            <li><%= link_to "КРАШЕНЫЙ МДФ", root_path %></li>
            <li><%= link_to "ПЛАСТИКОВЫЕ", root_path %></li>
            <li><%= link_to "МДФ РАМОЧНЫЙ", root_path %></li>
            <li><%= link_to "СТЕКЛО В АЛЮМ.ПРОФИЛЕ", root_path %></li>
            <li><%= link_to "ФОТОФАСАДЫ", root_path %></li>
          </ul>

          <div class="news">
            <%= image_tag("fasad-news.png", :alt => "ivm logo") %>
          </div>
        </div>
      </div>
      <div class="col-md-9 content-kitchens">

        <% @subcategory.each do |cat| %>
        <div class="block" style="margin-bottom:20px">
          <div class="main-title" data-toggle="modal" data-target="#mdf-modal"><%= cat.title %></div>
          <p><%= cat.description %></p>

          <div class="col-md-3">
            <a href="<%= cat.image_url %>" data-lighter>
              <%= image_tag(cat.image_url, :alt => "ivm logo") %>
              <%= image_tag("zoom.png", :alt => "ivm logo", class: 'zoom') %>
            </a>
          </div>
          <div class="line"></div>
        </div>
        <% end %>

      </div>
    </div>
  </div>
</div>



<div class="bd-example-3">
  <div class="modal fade" id="mdf-modal" tabindex="-1" role="dialog" aria-labelledby="mdf-modal-ModalLabel-2" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content mdf-modal">
        <div class="modal-body">
          <button type="button" class="close close-pos" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"><%= image_tag('close-img.png', class: "close-button") %></span>
          </button>
          <div class="col-md-8">
            <div id="owl-mdf" class="owl-carousel owl-theme">
              <div class="item">
                <%= image_tag("our-works-1.png", :alt => "ivm") %>
              </div>

              <div class="item">
                <%= image_tag("our-works-1.png", :alt => "ivm") %>
              </div>

              <div class="item">
                <%= image_tag("our-works-1.png", :alt => "ivm") %>
              </div>

              <div class="item">
                <%= image_tag("our-works-1.png", :alt => "ivm") %>
              </div>
            </div>
          </div>

          <div class="col-md-4">
            <h1 class="main-title">КРАШЕНЫЙ МДФ</h1>

            <div class="col-md-6 col-sm-6">
              <%= image_tag("k-1.png", :alt => "ivm") %>
            </div>

            <div class="col-md-6 col-sm-6">
              <%= image_tag("k-1.png", :alt => "ivm") %>
            </div>

            <div class="col-md-6 col-sm-6">
              <%= image_tag("k-1.png", :alt => "ivm") %>
            </div>

            <div class="col-md-6 col-sm-6">
              <%= image_tag("k-1.png", :alt => "ivm") %>
            </div>
            <div class="col-md-12 text">
              Чтобы узнать цену комплектации кухни
              по вашим размерам и предпочтениям
              Вы можете отправить заявку на расчет или
              заказать обратный звонок,
              и мы вам перезвоним!
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/ourworks.html.erb
<%= content_for :breadcrumbs do %>
  <ul class="list-group">
    <li class="list-group-item l"><%= link_to "ГЛАВНАЯ", root_path %></li>
    <li class="list-group-item"><%= link_to "НАШИ РАБОТЫ", ourworks_path %></li>
  </ul>
<% end %>

<div class="ourworks">
  <div class="container">
    <div class="row">

      <div class="col-slider-wrapper">
        <div class="form-slider">
          <div class="main-title">ОСТАВЬТЕ ЗАЯВКУ!</div>
          <div class="form">
            <div class="wrapper">
              <%= form_tag("", class: 'js-common-request', method: 'post') do %>
                <%= text_field_tag 'common[name]', nil, placeholder: 'Ваше имя', class: "name-user", :required => true %>
                <%= text_field_tag 'common[phone]', nil, placeholder: 'Номер телефона', pattern:'[+]\d{2}[(]\d{3}[)]\s\d{3}\s\d{2}\s\d{2}', class: "phone-user", :required => true %>
                <%= text_field_tag 'common[message]', nil, placeholder: 'Сообщения', class: "mess-user" %>
                <%= submit_tag("Отправить заявку", class: "btn-send-app-user") %>
              <% end %>
            </div>
          </div>
        </div>

        <div id="slick-ourworks" class="owl-theme" style="overflow: hidden;">
          <% 4.times do %>
            <div class="item-test" style="background-image: url(<%= asset_path('our-works-1.png') %>)"></div>
          <% end %>
        </div>


        <div class="text-center">МЫ ОБЛАДАЕМ БОЛЬШИМ ОПЫТОМ В ПРОЕКТИРОВАНИИ И ПРОИЗВОДСТВЕ МЕБЕЛИ! </div>
      </div>

      <div class="col-md-12 tabs-block">
        <div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
          <ul id="myTab" class="nav nav-tabs nav-tabs-responsive" role="tablist">
            <!--tab for all portfolios-->
            <li role="presentation" class="<%= 'active' if @show_project == 0 %>">
              <a href="#project-example-all" id="0-tab" role="tab" data-toggle="tab" aria-controls="0" aria-expanded="true">
                <span class="text">ВСЕ</span>
              </a>
            </li>
            <!--tabs for each category where at least one portfolio present-->
            <% @portfolios.map(&:category).uniq.each do |category| %>
              <li role="presentation" class="<%= 'active' if category.id == @show_project %>">
                <a href="#project-example-<%= category.id %>" id="0-tab" role="tab" data-toggle="tab" aria-controls="0" aria-expanded="true">
                  <span class="text"><%= category.title %></span>
                </a>
              </li>
            <% end %>
          </ul>

          <div id="myTabContent" class="tab-content">
            <!--tab content for all portfolios-->
            <div role="tabpanel" class="tab-pane fade in <%= 'active' if @show_project == 0 %>" id="project-example-all" aria-labelledby="0-tab">
              <% @portfolios.each do |portfolio| %>
                <div class="col-md-5ths each-element col-xs-4" data-toggle="modal-with-slider" data-target="<%= portfolio.id%>">
                  <%= image_tag portfolio.images.first.image_url(:medium_fill), alt: "ivm logo", class: 'background'  %>
                  <div class="image-text">
                    <%= image_tag "zoom.png", alt: "ivm logo", class: 'zoom'  %>
                    <span class="title"><%= portfolio.title %></span>
                  </div>
                </div>
              <% end %>
            </div>
            <!--tabs content for each category where at least one portfolio present-->
            <% portfolios = [] %>
            <% @portfolios.map(&:category).uniq.each do |category| %>
            <div role="tabpanel" class="tab-pane fade in <%= 'active' if category.id == @show_project %>" id="project-example-<%= category.id %>" aria-labelledby="0-tab">
              <% category.subcategories.map(&:portfolios).reject(&:empty?).flatten!.each do |portfolio| %>
                <% portfolios << portfolio %>
                <div class="col-md-5ths each-element col-xs-4" data-toggle="modal-with-slider" data-target="<%= portfolio.id%>">
                  <%= image_tag portfolio.images.first.image_url(:medium_fill), alt: "ivm logo", class: 'background'  %>
                  <div class="image-text">
                    <%= image_tag "zoom.png", alt: "ivm logo", class: 'zoom'  %>
                    <span class="title"><%= portfolio.title %></span>
                  </div>
                </div>
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% portfolios.each_with_index do |portfolio, i| %>
  <%= render 'partials/item_modal', item: portfolio, item_index: i, max_index: portfolios.count - 1 %>
<% end %>

<%= render 'subcategories/item_modals' %>